# -*- coding: utf-8 -*-
"""cyborg-seminar-topicmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z64nfSAD7yQk0i_MGGiw_tmxB2bX4Y_B

"""


#These are the settings of your search in reddit

# Usage instructions:
# choose keywords (at least one) separating with a comma like this ["k1", "k2"]
keywords = ["mind uploading"]
#choose subreddit (without r/)
subreddit_name = "transhuman"

#choose logic to combine keywords. I recommend not using more than 2 so as not to overload the reddit API (it would fail to produce results)
# "physical augmentation" AND "microchip" will return matches where both keywords are found
# "physical augmentation" OR "microchip" will return matches where either keyword is found.
#options are " AND ", " OR "
query = " OR ".join(keywords)

#This is where you gather (import) all the tools you'll need to run the topic model


import praw
import pandas as pd
from gensim import corpora
from gensim.models import LdaModel
from gensim.parsing.preprocessing import preprocess_string
from bertopic import BERTopic
#from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from bertopic.vectorizers import ClassTfidfTransformer
from umap import UMAP
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
from hdbscan import HDBSCAN
import plotly.io as pio

nltk.download('punkt')
nltk.download("stopwords")



#This is where you set up your authentication for reddit.
# look to the left of this panel. the fourth icon is a key.
# click there to paste your authentication data
# if asked, grant access


import praw
from google.colab import userdata

reddit = praw.Reddit(
    client_id=userdata.get('REDDIT_CLIENT_ID'),
    client_secret=userdata.get('REDDIT_CLIENT_SECRET'),
    user_agent="cyborg-seminar by u/cyborg_seminar",
)

# this is where you collect data from reddit.
# you should run it again every time you want to collect new data
# if you already have the data, don't run it again

# you will see a lot of warnings. it's my fault for not updating. ignore them xD

import pandas as pd
import json
import os
import re
from datetime import datetime


def sanitize_filename(text):
    """Convert text to a safe filename by removing/replacing invalid characters"""
    # Remove or replace characters that aren't allowed in filenames
    sanitized = re.sub(r'[<>:"/\\|?*]', '_', text)
    # Replace spaces with underscores
    sanitized = sanitized.replace(' ', '_')
    # Remove multiple consecutive underscores
    sanitized = re.sub(r'_+', '_', sanitized)
    # Limit length to avoid filesystem issues
    return sanitized[:100]

def create_filename(query, subreddit_name):
    """Create a filename based on query and subreddit"""
    query_clean = sanitize_filename(query.replace(' OR ', '_'))
    subreddit_clean = sanitize_filename(subreddit_name)
    timestamp = datetime.now().strftime("%Y%m%d")
    return f"data/{subreddit_clean}_{query_clean}_{timestamp}.csv"

def prepare_posts_for_csv(posts_data):
    """Convert posts data to CSV-friendly format with comments as JSON strings"""
    csv_data = []

    for post in posts_data:
        # Convert comments list to JSON string for CSV storage
        comments_json = json.dumps(post['comments']) if post['comments'] else "[]"

        post_row = {
            'post_id': post['id'],
            'title': post['title'],
            'selftext': post['selftext'],
            'author': post['author'],
            'created_utc': post['created_utc'],
            'url': post['url'],
            'comments': comments_json,
            'comment_count': len(post['comments'])
        }
        csv_data.append(post_row)

    return csv_data

def save_to_csv_with_deduplication(posts_data, query, subreddit_name):
    """Save posts data to CSV with deduplication if file exists"""
    filename = create_filename(query, subreddit_name)

    # Prepare new data
    new_csv_data = prepare_posts_for_csv(posts_data)
    new_df = pd.DataFrame(new_csv_data)

    if os.path.exists(filename):
        print(f"File {filename} exists. Loading and deduplicating...")

        # Load existing data
        existing_df = pd.read_csv(filename)

        # Convert comments column back to lists for processing
        def parse_comments(comments_str):
            try:
                return json.loads(comments_str) if comments_str != "[]" else []
            except:
                return []

        # Combine dataframes
        combined_df = pd.concat([existing_df, new_df], ignore_index=True)

        # Remove duplicates based on post_id
        original_count = len(combined_df)
        combined_df = combined_df.drop_duplicates(subset=['post_id'], keep='first')
        duplicates_removed = original_count - len(combined_df)

        print(f"Removed {duplicates_removed} duplicate posts")
        final_df = combined_df
    else:
        print(f"Creating new file {filename}")
        final_df = new_df

    # Save to CSV
    final_df.to_csv(filename, index=False)
    print(f"Saved {len(final_df)} posts to {filename}")

    return filename, final_df

def load_and_parse_csv(filename):
    """Load CSV and convert comments back to Python objects for analysis"""
    df = pd.read_csv(filename)

    # Parse comments back to lists
    df['comments_parsed'] = df['comments'].apply(
        lambda x: json.loads(x) if x != "[]" else []
    )

    return df

# Your existing fetch function with author names added
def fetch_posts_and_comments(subreddit_name, query, limit=100): #<- API LIMITS TO 1000 requests/second, can be reached with comments. Keep low (100 is ok)
    subreddit = reddit.subreddit(subreddit_name)
    search_results = subreddit.search(query, limit=limit)
    posts_data = []

    for post in search_results:
        # Get post author, handle deleted/suspended accounts
        try:
            post_author = post.author.name if post.author else "[deleted]"
        except AttributeError:
            post_author = "[deleted]"

        post_data = {
            "title": post.title,
            "selftext": post.selftext,
            "author": post_author,
            "created_utc": post.created_utc,
            "url": post.url,
            "id": post.id,
            "comments": []
        }

        # Collect top-level comments
        if post.comments:
            post.comments.replace_more(limit=5)
            for comment in post.comments.list():
                # Filter out bot or removed comments
                if len(comment.body) < 10 or "I am a bot" in comment.body or \
                   "[deleted]" in comment.body or "[removed]" in comment.body:
                    continue

                # Get comment author, handle deleted/suspended accounts
                try:
                    comment_author = comment.author.name if comment.author else "[deleted]"
                except AttributeError:
                    comment_author = "[deleted]"

                post_data["comments"].append({
                    "body": comment.body,
                    "author": comment_author,
                    "created_utc": comment.created_utc
                })
        posts_data.append(post_data)

    return posts_data

# Fetch the data
posts_and_comments = fetch_posts_and_comments(subreddit_name, query)

# Display results
print(f"Found {len(posts_and_comments)} posts matching the keywords.")
for post in posts_and_comments[:3]:
    print(f"Title: {post['title']}")
    print(f"URL: {post['url']}")
    print(f"Number of Comments: {len(post['comments'])}")
    print()

# Save to CSV with automatic deduplication
filename, df = save_to_csv_with_deduplication(posts_and_comments, query, subreddit_name)
print(f"Data saved to: {filename}")

# Display statistics
total_comments = df['comment_count'].sum()
print(f"\nData Summary:")
print(f"Total posts: {len(df)}")
print(f"Total comments: {total_comments}")
print(f"Average comments per post: {total_comments/len(df):.1f}")

#this is where you are collecting all the data you downloaded
#this is what will be fed to the topic model

import pandas as pd
import glob
import re
import os
from typing import List, Optional
import emoji

def aggregate_csv_files(directory_path: str, file_pattern: str = "*.csv") -> pd.DataFrame:
    """
    Aggregates all CSV files in a directory into a single dataframe and deduplicates by post_id.

    Parameters:
    directory_path (str): Path to directory containing CSV files
    file_pattern (str): File pattern to match (default: "*.csv")

    Returns:
    pd.DataFrame: Aggregated and deduplicated dataframe
    """
    # Get all CSV files matching the pattern
    csv_files = glob.glob(os.path.join(directory_path, file_pattern))

    if not csv_files:
        raise ValueError(f"No CSV files found in {directory_path} matching pattern {file_pattern}")

    print(f"Found {len(csv_files)} CSV files to aggregate")

    # Read and concatenate all CSV files
    dataframes = []
    for file in csv_files:
        try:
            df = pd.read_csv(file)
            dataframes.append(df)
            print(f"Loaded {file}: {len(df)} rows")
        except Exception as e:
            print(f"Error reading {file}: {e}")

    if not dataframes:
        raise ValueError("No valid CSV files could be loaded")

    # Concatenate all dataframes
    combined_df = pd.concat(dataframes, ignore_index=True)
    print(f"Combined dataframe: {len(combined_df)} rows")

    # Deduplicate by post_id (assuming this column exists)
    if 'post_id' in combined_df.columns:
        initial_count = len(combined_df)
        combined_df = combined_df.drop_duplicates(subset=['post_id'])
        print(f"Removed {initial_count - len(combined_df)} duplicate posts")
    else:
        print("Warning: 'post_id' column not found, skipping deduplication")

    print(f"Final aggregated dataframe: {len(combined_df)} rows")
    return combined_df

def unroll_comments(df: pd.DataFrame) -> pd.DataFrame:
    """
    Unrolls Reddit posts and comments into separate rows with standardized columns.

    Combines title and selftext for posts, extracts individual comments,
    and creates standardized columns for content_type, text, post_id, author, and timestamp.

    Parameters:
    df (pd.DataFrame): Input dataframe with Reddit data structure

    Returns:
    pd.DataFrame: Dataframe with unrolled posts and comments
    """
    import json

    unrolled_rows = []

    for idx, row in df.iterrows():
        # Create post row - combine title and selftext
        post_text = ""
        if pd.notna(row.get('title')):
            post_text = str(row['title'])
        if pd.notna(row.get('selftext')) and str(row['selftext']).strip():
            if post_text:
                post_text += " " + str(row['selftext'])
            else:
                post_text = str(row['selftext'])

        # Add the main post
        post_row = {
            'post_id': row['post_id'],
            'content_type': 'post',
            'text': post_text.strip(),
            'author': row.get('author', ''),
            'timestamp': row.get('created_utc', ''),
            'url': row.get('url', ''),
            'title': row.get('title', ''),
            'comment_count': row.get('comment_count', 0)
        }
        unrolled_rows.append(post_row)

        # Process comments if they exist
        if 'comments' in df.columns and pd.notna(row['comments']):
            comments_data = row['comments']

            # Parse comments from JSON string format
            if isinstance(comments_data, str):
                try:
                    comments_list = json.loads(comments_data)
                except json.JSONDecodeError:
                    print(f"Warning: Could not parse comments for post {row['post_id']}")
                    continue
            elif isinstance(comments_data, list):
                comments_list = comments_data
            else:
                continue

            # Create a row for each comment
            for comment in comments_list:
                if isinstance(comment, dict) and 'body' in comment:
                    comment_body = comment['body']
                    if comment_body and str(comment_body).strip():
                        comment_row = {
                            'post_id': row['post_id'],
                            'content_type': 'comment',
                            'text': str(comment_body).strip(),
                            'author': comment.get('author', ''),
                            'timestamp': comment.get('created_utc', ''),
                            'url': row.get('url', ''),  # Link back to original post URL
                            'title': row.get('title', ''),  # Keep original post title for reference
                            'comment_count': row.get('comment_count', 0)
                        }
                        unrolled_rows.append(comment_row)
                elif isinstance(comment, str) and comment.strip():
                    # Handle simple string comments (fallback)
                    comment_row = {
                        'post_id': row['post_id'],
                        'content_type': 'comment',
                        'text': str(comment).strip(),
                        'author': '',
                        'timestamp': '',
                        'url': row.get('url', ''),
                        'title': row.get('title', ''),
                        'comment_count': row.get('comment_count', 0)
                    }
                    unrolled_rows.append(comment_row)

    # Create new dataframe
    unrolled_df = pd.DataFrame(unrolled_rows)

    # Add some useful derived columns
    unrolled_df['text_length'] = unrolled_df['text'].str.len()
    unrolled_df['is_post'] = unrolled_df['content_type'] == 'post'
    unrolled_df['is_comment'] = unrolled_df['content_type'] == 'comment'

    print(f"Unrolled {len(df)} posts into {len(unrolled_df)} content items")
    print(f"  - Posts: {unrolled_df['is_post'].sum()}")
    print(f"  - Comments: {unrolled_df['is_comment'].sum()}")

    return unrolled_df

def filter_by_token_length(df: pd.DataFrame,
                          content_column: str = 'content',
                          min_tokens: int = 30) -> pd.DataFrame:
    """
    Eliminates rows with content shorter than specified token count.

    Parameters:
    df (pd.DataFrame): Input dataframe
    content_column (str): Name of the content column to check
    min_tokens (int): Minimum number of tokens required

    Returns:
    pd.DataFrame: Filtered dataframe
    """
    def count_tokens(text):
        """Simple token counting by splitting on whitespace"""
        if pd.isna(text) or text == "":
            return 0
        return len(str(text).split())

    # Count tokens for each row
    df['token_count'] = df[content_column].apply(count_tokens)

    # Filter rows
    initial_count = len(df)
    filtered_df = df[df['token_count'] >= min_tokens].copy()

    # Drop the temporary token_count column
    filtered_df = filtered_df.drop('token_count', axis=1)

    print(f"Filtered from {initial_count} to {len(filtered_df)} rows (removed {initial_count - len(filtered_df)} short texts)")
    return filtered_df

def clean_text(df: pd.DataFrame,
               content_column: str = 'text') -> pd.DataFrame:
    """
    Removes emojis and URLs from text content.

    Parameters:
    df (pd.DataFrame): Input dataframe
    content_column (str): Name of the content column to clean (default: 'text')

    Returns:
    pd.DataFrame: Dataframe with cleaned text
    """
    def remove_emojis_and_urls(text):
        if pd.isna(text):
            return ""

        text = str(text)

        # Remove URLs (http/https and www patterns)
        url_pattern = r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
        text = re.sub(url_pattern, '', text)

        www_pattern = r'www\.(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
        text = re.sub(www_pattern, '', text)

        # Remove reddit-style links
        reddit_pattern = r'r/[A-Za-z0-9_]+'
        text = re.sub(reddit_pattern, '', text)

        user_pattern = r'u/[A-Za-z0-9_]+'
        text = re.sub(user_pattern, '', text)

        email_pattern = r'[A-Za-z0-9_]+@[A-Za-z0-9_]+'
        text = re.sub(email_pattern, '', text)

        # Remove emojis using emoji library
        text = emoji.replace_emoji(text, replace='')

        # Remove extra whitespace
        text = re.sub(r'\s+', ' ', text).strip()

        return text

    # Apply cleaning
    df_cleaned = df.copy()
    df_cleaned[content_column] = df_cleaned[content_column].apply(remove_emojis_and_urls)

    print(f"Cleaned text content in {len(df_cleaned)} rows")
    return df_cleaned

def process_reddit_data_pipeline(directory_path: str,
                                file_pattern: str = "data/*.csv",
                                min_tokens: int = 30) -> pd.DataFrame:
    """
    Complete pipeline to process Reddit CSV data.

    Parameters:
    directory_path (str): Path to directory containing CSV files
    file_pattern (str): File pattern to match
    min_tokens (int): Minimum token count threshold

    Returns:
    pd.DataFrame: Processed dataframe
    """
    print("=== Reddit Data Processing Pipeline ===")

    # Step 1: Aggregate CSV files and deduplicate
    print("\n1. Aggregating CSV files...")
    df = aggregate_csv_files(directory_path, file_pattern)
    combined_df = df
    # Step 2: Unroll comments
    print("\n2. Unrolling comments...")
    df = unroll_comments(df)

    #df.head()

    # Step 3: Filter by token length
    print("\n3. Filtering by token length...")
    df = filter_by_token_length(df, content_column='text', min_tokens=min_tokens)

    # Step 4: Clean text
    print("\n4. Cleaning text...")
    df = clean_text(df, content_column='text')

    print(f"\n=== Pipeline Complete ===")
    print(f"Final dataset: {len(df)} rows")

    return df, combined_df

processed_df, combined_df = process_reddit_data_pipeline(
    directory_path=".",
    min_tokens=30
)


#look at the data, ready for bertopic!

processed_df.head()

#analyze document size statistics

import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt

def count_tokens(text):
    """Simple token counting by splitting on whitespace"""
    if pd.isna(text) or text == "":
        return 0
    return len(str(text).split())

def analyze_document_lengths(df, text_column='text'):
    """
    Analyze document lengths and provide statistics on token counts.

    Parameters:
    df (pd.DataFrame): Input dataframe
    text_column (str): Name of the text column to analyze

    Returns:
    dict: Statistics about document lengths
    """
    print("=== Document Length Analysis ===")

    # Calculate token counts
    df['token_count'] = df[text_column].apply(count_tokens)

    # Basic statistics
    stats = {
        'total_documents': len(df),
        'mean_tokens': df['token_count'].mean(),
        'median_tokens': df['token_count'].median(),
        'std_tokens': df['token_count'].std(),
        'min_tokens': df['token_count'].min(),
        'max_tokens': df['token_count'].max(),
        'q75_tokens': df['token_count'].quantile(0.75),
        'q90_tokens': df['token_count'].quantile(0.90),
        'q95_tokens': df['token_count'].quantile(0.95),
        'q99_tokens': df['token_count'].quantile(0.99),
        'above_512': (df['token_count'] > 512).sum(),
        'above_512_pct': (df['token_count'] > 512).mean() * 100,
        'above_256': (df['token_count'] > 256).sum(),
        'above_256_pct': (df['token_count'] > 256).mean() * 100,
        'above_1000': (df['token_count'] > 1000).sum(),
        'above_1000_pct': (df['token_count'] > 1000).mean() * 100
    }

    # Print statistics
    print(f"Total documents: {stats['total_documents']:,}")
    print(f"\\nToken Count Statistics:")
    print(f"  Mean: {stats['mean_tokens']:.1f}")
    print(f"  Median: {stats['median_tokens']:.1f}")
    print(f"  Std Dev: {stats['std_tokens']:.1f}")
    print(f"  Min: {stats['min_tokens']}")
    print(f"  Max: {stats['max_tokens']}")
    print(f"  75th percentile: {stats['q75_tokens']:.1f}")
    print(f"  90th percentile: {stats['q90_tokens']:.1f}")
    print(f"  95th percentile: {stats['q95_tokens']:.1f}")
    print(f"  99th percentile: {stats['q99_tokens']:.1f}")

    print(f"\\nDocuments exceeding common limits:")
    print(f"  Above 256 tokens: {stats['above_256']:,} ({stats['above_256_pct']:.1f}%)")
    print(f"  Above 512 tokens: {stats['above_512']:,} ({stats['above_512_pct']:.1f}%)")
    print(f"  Above 1000 tokens: {stats['above_1000']:,} ({stats['above_1000_pct']:.1f}%)")

    # Content type breakdown
    if 'content_type' in df.columns:
        print(f"\\nBy Content Type:")
        for content_type in df['content_type'].unique():
            subset = df[df['content_type'] == content_type]
            above_512 = (subset['token_count'] > 512).sum()
            pct_above_512 = (subset['token_count'] > 512).mean() * 100
            print(f"  {content_type}: {above_512:,}/{len(subset):,} above 512 tokens ({pct_above_512:.1f}%)")

    return stats

def truncate_by_paragraph(text, max_tokens=512):
    """
    Truncate text by complete paragraphs to stay under token limit.

    Parameters:
    text (str): Input text
    max_tokens (int): Maximum number of tokens

    Returns:
    str: Truncated text
    """
    if pd.isna(text) or text == "":
        return ""

    text = str(text)

    # Count tokens in full text
    if count_tokens(text) <= max_tokens:
        return text

    # Split by paragraphs (double newlines, single newlines, or sentences)
    # Try multiple paragraph splitting strategies
    paragraphs = []

    # Strategy 1: Double newlines (true paragraphs)
    if '\\n\\n' in text:
        paragraphs = text.split('\\n\\n')
    # Strategy 2: Single newlines
    elif '\\n' in text:
        paragraphs = text.split('\\n')
    # Strategy 3: Sentences (periods followed by space and capital letter)
    else:
        # Split by sentences
        sentence_pattern = r'(?<=[.!?])\\s+(?=[A-Z])'
        paragraphs = re.split(sentence_pattern, text)

    # Build truncated text paragraph by paragraph
    truncated_parts = []
    current_tokens = 0

    for paragraph in paragraphs:
        paragraph = paragraph.strip()
        if not paragraph:
            continue

        paragraph_tokens = count_tokens(paragraph)

        # If adding this paragraph would exceed limit, stop
        if current_tokens + paragraph_tokens > max_tokens:
            break

        truncated_parts.append(paragraph)
        current_tokens += paragraph_tokens

    # Join paragraphs back together
    if '\\n\\n' in text:
        truncated_text = '\\n\\n'.join(truncated_parts)
    elif '\\n' in text:
        truncated_text = '\\n'.join(truncated_parts)
    else:
        truncated_text = ' '.join(truncated_parts)

    return truncated_text

def truncate_long_documents(df, text_column='text', max_tokens=512):
    """
    Truncate documents that exceed the token limit.

    Parameters:
    df (pd.DataFrame): Input dataframe
    text_column (str): Name of the text column
    max_tokens (int): Maximum number of tokens

    Returns:
    pd.DataFrame: Dataframe with truncated documents
    """
    print(f"\\n=== Truncating documents above {max_tokens} tokens ===")

    df_truncated = df.copy()

    # Identify long documents
    df_truncated['original_token_count'] = df_truncated[text_column].apply(count_tokens)
    long_docs_mask = df_truncated['original_token_count'] > max_tokens
    num_long_docs = long_docs_mask.sum()

    print(f"Documents to truncate: {num_long_docs:,}")

    if num_long_docs == 0:
        print("No documents need truncation.")
        return df_truncated.drop('original_token_count', axis=1)

    # Apply truncation to long documents
    def truncate_if_needed(row):
        if row['original_token_count'] > max_tokens:
            return truncate_by_paragraph(row[text_column], max_tokens)
        return row[text_column]

    df_truncated[text_column] = df_truncated.apply(truncate_if_needed, axis=1)

    # Calculate new token counts
    df_truncated['new_token_count'] = df_truncated[text_column].apply(count_tokens)

    # Statistics on truncation
    truncated_subset = df_truncated[long_docs_mask]
    avg_original = truncated_subset['original_token_count'].mean()
    avg_new = truncated_subset['new_token_count'].mean()
    avg_reduction = avg_original - avg_new

    print(f"Truncation results:")
    print(f"  Average original length: {avg_original:.1f} tokens")
    print(f"  Average new length: {avg_new:.1f} tokens")
    print(f"  Average reduction: {avg_reduction:.1f} tokens")
    print(f"  Documents still above {max_tokens}: {(df_truncated['new_token_count'] > max_tokens).sum()}")

    # Clean up temporary columns
    df_final = df_truncated.drop(['original_token_count', 'new_token_count'], axis=1)

    return df_final

def plot_token_distribution(df, text_column='text', max_display=2000):
    """
    Plot histogram of token counts.

    Parameters:
    df (pd.DataFrame): Input dataframe
    text_column (str): Name of the text column
    max_display (int): Maximum token count to display on x-axis
    """
    # Calculate token counts if not already present
    if 'token_count' not in df.columns:
        df['token_count'] = df[text_column].apply(count_tokens)

    plt.figure(figsize=(12, 6))

    # Create histogram
    token_counts = df['token_count'].clip(upper=max_display)

    plt.hist(token_counts, bins=50, alpha=0.7, edgecolor='black')
    plt.axvline(x=512, color='red', linestyle='--', label='512 token limit')
    plt.axvline(x=256, color='orange', linestyle='--', label='256 token limit')

    plt.xlabel('Token Count')
    plt.ylabel('Number of Documents')
    plt.title('Distribution of Document Token Counts')
    plt.legend()
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()


# Analyze document lengths
stats = analyze_document_lengths(processed_df)

# Plot distribution
plot_token_distribution(processed_df)

# Truncate long documents if needed
if stats['above_512'] > 0:
    print(f"\\nTruncating {stats['above_512']} documents above 512 tokens...")
    processed_df_truncated = truncate_long_documents(processed_df, max_tokens=512)

    # Re-analyze after truncation
    print(f"\\n=== After Truncation ===")
    final_stats = analyze_document_lengths(processed_df_truncated)
    plot_token_distribution(processed_df_truncated)
else:
    print("\\nNo documents need truncation.")
    processed_df_truncated = processed_df

# this is where the topic modelling happens. it may take a while

import logging
import pandas as pd
import numpy as np
from bertopic import BERTopic
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from sentence_transformers import SentenceTransformer
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import plotly.graph_objects as go
import plotly.express as px
from bertopic.representation import MaximalMarginalRelevance


def setup_bertopic_model(
    min_cluster_size=15,
    min_samples=5,
    n_neighbors=15,
    n_components=10,
    diversity=0.7,
    top_n_words=15,
    random_state=42
):
    """
    Set up BERTopic model with optimized parameters for imaginaries research.

    Parameters:
    min_cluster_size (int): Minimum size for HDBSCAN clusters
    min_samples (int): Minimum samples for HDBSCAN
    n_neighbors (int): UMAP n_neighbors parameter
    n_components (int): UMAP dimensionality reduction
    diversity (float): Topic diversity parameter
    top_k_words (int): Number of words per topic
    random_state (int): Random seed for reproducibility

    Returns:
    BERTopic: Configured BERTopic model
    """
    print("=== Setting up BERTopic Model ===")


    # Embedding model - using a model good for social media text
    embedding_model = SentenceTransformer('all-MiniLM-L12-v2')
    print(f"Embedding model: {embedding_model}")

    # UMAP for dimensionality reduction
    umap_model = UMAP(
        n_neighbors=n_neighbors,
        n_components=n_components,
        min_dist=0.0,
        metric='cosine',
        random_state=random_state
    )
    print(f"UMAP parameters: n_neighbors={n_neighbors}, n_components={n_components}")

    # HDBSCAN for clustering
    hdbscan_model = HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        metric='euclidean',
        cluster_selection_method='eom',
        prediction_data=True
    )
    print(f"HDBSCAN parameters: min_cluster_size={min_cluster_size}, min_samples={min_samples}")

    # Vectorizer for topic representation
    vectorizer_model = CountVectorizer(
        ngram_range=(1, 2),  # Include bigrams for better topic representation
        stop_words='english',
        max_features=4000,
        min_df=2,  # Word must appear in at least 2 documents
        max_df=0.95  # Word can't appear in more than 95% of documents
    )
    print("Vectorizer: ngrams(1,2), stop_words=english, max_features=5000")

    representation_model = MaximalMarginalRelevance(diversity=diversity)

    # Initialize BERTopic
    topic_model = BERTopic(
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer_model,
        representation_model=representation_model,
        top_n_words=top_n_words,
        calculate_probabilities=True,  # For uncertainty analysis
        verbose=True,
        nr_topics="auto"
    )

    print(f"BERTopic configured with diversity={diversity}, top_n_words={top_n_words}")
    print("=== Model Setup Complete ===\\n")

    return topic_model

def fit_topic_model(topic_model, df, text_column='text'):
    """
    Fit the BERTopic model on the dataset.

    Parameters:
    topic_model (BERTopic): Configured BERTopic model
    df (pd.DataFrame): Input dataframe
    text_column (str): Name of text column

    Returns:
    tuple: (fitted_model, topics, probabilities)
    """
    print("=== Fitting BERTopic Model ===")

    # Prepare documents
    documents = df[text_column].tolist()
    print(f"Total documents: {len(documents):,}")

    # Remove empty documents
    documents = [doc for doc in documents if doc and str(doc).strip()]
    print(f"Non-empty documents: {len(documents):,}")

    if len(documents) == 0:
        raise ValueError("No valid documents found for topic modeling")

    # Fit the model
    print("\nFitting model (this may take several minutes)...")
    topics, probabilities = topic_model.fit_transform(documents)



    print(f"\nModel fitting complete!")
    print(f"Number of topics found: {len(set(topics)) - 1}")  # -1 to exclude outlier topic
    print(f"Outlier documents (topic -1): {(np.array(topics) == -1).sum()}")

    return topic_model, topics, probabilities, documents

# Step 1: Setup model
topic_model = setup_bertopic_model( # ---------------------------------- you can play around with these parameters
    min_cluster_size=50,     # Good for detailed topics
    min_samples=3,           # Conservative clustering
    n_neighbors=15,          # Standard UMAP parameter
    n_components=15,         # Moderate dimensionality
    diversity=0.6,           # Encourage topic diversity
    top_n_words=15,          # More keywords for interpretation
    random_state=42          # Reproducibility
)

# Step 2: Fit model
#topic_model, topics, probabilities, documents = fit_topic_model(topic_model, df, text_column)
topic_model, topics, probabilities, documents = fit_topic_model(topic_model, processed_df, 'text')

topic_model.visualize_barchart(top_n_topics=10).show()

# visualize topics over time

# Convert timestamps to proper datetime
processed_df['timestamp'] = pd.to_datetime(processed_df['timestamp'], unit='s')

# Optionally, round or truncate to month if you don’t need daily precision
processed_df['timestamp'] = processed_df['timestamp'].dt.to_period('M').dt.to_timestamp()

# Then run BERTopic
topics_over_time = topic_model.topics_over_time(
    processed_df['text'].tolist(),
    processed_df['timestamp'].tolist(),
    nr_bins=20
)

topic_model.visualize_topics_over_time(topics_over_time)

fig2 = topic_model.visualize_topics(title="Intertopic Distance Map")

fig2.show()

fig3 = topic_model.visualize_hierarchy(title="Topic Hierarchy")
fig3.show()

# this is the starting point of your qualitative analysis. extract representative documents and code them manually
# the documents will be saved in the folder representative_docs, you can access it from the menu on your left

import pandas as pd
import os
import re
from collections import Counter

def export_representative_documents(topic_model, topics, documents, df,
                                  n_topics=10, docs_per_topic=3,
                                  output_dir="representative_docs"):
    """
    Export representative documents for top N topics to individual .txt files for MaxQDA coding.

    Parameters:
    topic_model: Fitted BERTopic model
    topics (list): Topic assignments for each document
    documents (list): List of documents
    df (pd.DataFrame): Original dataframe with metadata (author, post_id columns)
    n_topics (int): Number of top topics to export (default: 10)
    docs_per_topic (int): Number of representative documents per topic (default: 3)
    output_dir (str): Directory to save files (default: "maxqda_topics")

    Returns:
    dict: Export summary with file paths and topic information
    """

    print(f"Exporting Representative Documents for MaxQDA")
    print(f"   Topics: {n_topics}")
    print(f"   Documents per topic: {docs_per_topic}")
    print(f"   Output directory: {output_dir}")
    print("=" * 50)

    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Get topic frequencies and select top topics (excluding outlier topic -1)
    topic_counts = Counter(topics)
    topic_counts.pop(-1, None)  # Remove outlier topic
    top_topics = [topic_id for topic_id, count in topic_counts.most_common(n_topics)]

    # Prepare document data
    doc_data = pd.DataFrame({
        'document': documents,
        'topic': topics,
        'author': df['author'].values[:len(documents)],
        'post_id': df['post_id'].values[:len(documents)],
        'doc_index': range(len(documents))
    })

    export_summary = {
        'topic_files': {},
        'total_files': 0,
        'total_documents': 0
    }

    # Export documents for each top topic
    for topic_id in top_topics:
        # Get topic information
        topic_words = topic_model.get_topic(topic_id)
        topic_label = ", ".join([word for word, score in topic_words[:5]])

        # Get all documents for this topic
        topic_docs = doc_data[doc_data['topic'] == topic_id]

        if len(topic_docs) == 0:
            print(f"⚠️  Topic {topic_id}: No documents found")
            continue

        # Get representative documents directly from BERTopic
        representative_docs = topic_model.get_representative_docs(topic_id)
        #print(representative_docs)

        if not representative_docs:
            print(f"⚠️  Topic {topic_id}: No representative documents found")
            continue

        # Create clean filename
        clean_label = re.sub(r'[^a-zA-Z0-9\s]', '', topic_label)
        clean_label = re.sub(r'\s+', '_', clean_label)[:50]  # Limit length
        filename = f"topic_{topic_id:03d}_{clean_label}.txt"
        filepath = os.path.join(output_dir, filename)

        # Write documents to file
        with open(filepath, 'w', encoding='utf-8') as f:
            # Write header with topic information
            f.write(f"TOPIC {topic_id}: {topic_label}\n")
            f.write(f"Keywords: {', '.join([f'{word}({score:.3f})' for word, score in topic_words[:10]])}\n")
            f.write("=" * 80 + "\n\n")

            # Write representative documents directly
            f.write("REPRESENTATIVE DOCUMENTS:\n")
            f.write("-" * 40 + "\n\n")

            for idx, doc in enumerate(representative_docs, 1):
                f.write(f"DOCUMENT {idx}\n")
                f.write("-" * 20 + "\n")
                f.write(f"{doc}\n")
                f.write("\n" + "=" * 40 + "\n\n")

        # Store export information
        export_summary['topic_files'][topic_id] = {
            'filename': filename,
            'filepath': filepath,
            'label': topic_label,
            'num_representative_docs': len(representative_docs)
        }

        export_summary['total_files'] += 1
        export_summary['total_documents'] += len(representative_docs)

        print(f"✅ Topic {topic_id:3d}: {len(representative_docs):2d} docs → {filename}")

    print(f"\nExported {export_summary['total_files']} topic files")
    print(f"Total documents: {export_summary['total_documents']}")
    print(f"Location: {os.path.abspath(output_dir)}")

    return export_summary

# Example usage:
export_summary = export_representative_documents(
    topic_model=topic_model,
    topics=topics,
    documents=documents,
    df=processed_df,
    n_topics=121,
    docs_per_topic=3
)

# if you need more documents for a specific topic, you can extract them with this

import random
import pandas as pd
import os
from typing import List, Union

def extract_topic_documents(topic_model,
                          documents: List[str],
                          topics_to_extract: List[int],
                          sample_size: int = 10,
                          output_dir: str = "ADDITIONAL_TOPIC_SAMPLES",
                          filename_prefix: str = "topic",
                          include_metadata: bool = True,
                          dataframe: pd.DataFrame = None,
                          metadata_columns: List[str] = None,
                          random_seed: int = None):
    """
    Extract random sample of documents for specified topics and save to text files.

    Parameters:
    -----------
    topic_model : BERTopic model
        Fitted BERTopic model
    documents : List[str]
        List of documents that were used to fit the topic model
    topics_to_extract : List[int]
        List of topic IDs to extract documents for
    sample_size : int, default=10
        Number of random documents to sample per topic
    output_dir : str, default="topic_samples"
        Directory to save the text files
    filename_prefix : str, default="topic"
        Prefix for the output filenames
    include_metadata : bool, default=True
        Whether to include document metadata (if available)
    dataframe : pd.DataFrame, optional
        Original dataframe containing the documents and metadata
    metadata_columns : List[str], optional
        Columns to include as metadata (e.g., ['timestamp', 'author', 'score'])
    random_seed : int, optional
        Random seed for reproducible sampling

    Returns:
    --------
    dict : Dictionary with topic IDs as keys and lists of sampled documents as values
    """

    if random_seed is not None:
        random.seed(random_seed)

    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Get topic assignments for all documents
    if hasattr(topic_model, 'topics_'):
        doc_topics = topic_model.topics_
    else:
        raise ValueError("Topic model must be fitted first. Run fit_transform() on your documents.")

    # Dictionary to store results
    sampled_docs = {}

    # Process each topic
    for topic_id in topics_to_extract:
        print(f"Processing Topic {topic_id}...")

        # Find all documents assigned to this topic
        topic_doc_indices = [i for i, topic in enumerate(doc_topics) if topic == topic_id]

        if not topic_doc_indices:
            print(f"  Warning: No documents found for topic {topic_id}")
            continue

        print(f"  Found {len(topic_doc_indices)} documents for topic {topic_id}")

        # Sample random documents (or all if fewer than sample_size)
        actual_sample_size = min(sample_size, len(topic_doc_indices))
        sampled_indices = random.sample(topic_doc_indices, actual_sample_size)

        # Extract the documents
        sampled_documents = [documents[i] for i in sampled_indices]
        sampled_docs[topic_id] = sampled_documents

        # Create filename
        filename = f"{filename_prefix}_{topic_id}_sample_{actual_sample_size}docs.txt"
        filepath = os.path.join(output_dir, filename)

        # Write to file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"TOPIC {topic_id} - RANDOM SAMPLE ({actual_sample_size} documents)\n")
            f.write("=" * 60 + "\n\n")

            # Get topic info if available
            try:
                topic_words = topic_model.get_topic(topic_id)
                if topic_words:
                    f.write("TOP KEYWORDS: ")
                    f.write(", ".join([word for word, _ in topic_words[:10]]))
                    f.write("\n\n")
            except:
                pass

            # Write each document
            for idx, (doc_idx, doc) in enumerate(zip(sampled_indices, sampled_documents)):
                f.write(f"--- DOCUMENT {idx + 1} (Index: {doc_idx}) ---\n")

                # Add metadata if available
                if include_metadata and dataframe is not None and metadata_columns:
                    f.write("METADATA:\n")
                    for col in metadata_columns:
                        if col in dataframe.columns:
                            try:
                                value = dataframe.iloc[doc_idx][col]
                                f.write(f"  {col}: {value}\n")
                            except:
                                f.write(f"  {col}: N/A\n")
                    f.write("\n")

                # Write the document text
                f.write("TEXT:\n")
                f.write(doc)
                f.write("\n\n" + "=" * 40 + "\n\n")

        print(f"  Saved {actual_sample_size} documents to {filepath}")

    print(f"\nCompleted! Files saved to '{output_dir}' directory")
    return sampled_docs



sampled_docs = extract_topic_documents(
    topic_model=topic_model,
    documents=processed_df['text'].tolist(),
    topics_to_extract=[1],  # Your topics of interest <-------------- ADD TOPIC NUMBER HERE
    sample_size=10, # number of additional documents <--------------- ADD NUMBER HERE
    output_dir="qualitative_coding_samples",
    filename_prefix="topic",
    include_metadata=True,
    dataframe=processed_df,
    metadata_columns=['timestamp', 'author', 'subreddit'],
    random_seed=42  # For reproducibility
)